//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int CId { get; set; }
        public string CName { get; set; }
        public string CProject { get; set; }
        public string CCompany { get; set; }
        public string CCNIC { get; set; }
        public string CAddress { get; set; }
        public string CPhoneNo { get; set; }
        public string CEmail { get; set; }
    }
}
