//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public int PId { get; set; }
        public string PName { get; set; }
        public Nullable<System.DateTime> PStartDate { get; set; }
        public Nullable<System.DateTime> PEndDate { get; set; }
        public string PTeamLead { get; set; }
        public string PCategory { get; set; }
    }
}
