//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SM
    {
        public int MId { get; set; }
        public string MContactNo { get; set; }
        public string MDateTime { get; set; }
        public string MType { get; set; }
    }
}
