//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int SId { get; set; }
        public string SName { get; set; }
        public string SPhoneNo { get; set; }
        public string SCompany { get; set; }
        public string SAddress { get; set; }
        public string SType { get; set; }
        public string SEmail { get; set; }
        public string SDetails { get; set; }
    }
}
