//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int TId { get; set; }
        public string TContactNo { get; set; }
        public string TCallType { get; set; }
        public string TCallDuration { get; set; }
        public string TDateTime { get; set; }
    }
}
